# Render Blueprint configuration to deploy the app in Week - 2/Day - 3

databases:
  - name: training_tracker_db # Name for the Render database service
    plan: free # Or choose a paid plan
    databaseName: training_tracker # Actual DB name
    user: training_tracker_user # DB user

services:
  - type: web
    plan: free # Or choose a paid plan
    name: training-tracker-app # Name for the Render web service
    runtime: python
    rootDir: Week - 2/Day - 6 # Set the root directory for build/start commands
    buildCommand: "./build.sh" # Runs from rootDir (Week - 2/Day - 3)
    startCommand: "python -m gunicorn training_tracker.asgi:application -k uvicorn.workers.UvicornWorker" # Runs from rootDir
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: training_tracker_db # Match the database service name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render generates a secure key
      - key: WEB_CONCURRENCY
        value: 4 # Adjust based on plan/needs
      - key: PYTHON_VERSION
        value: '3.10.11' # Specify full major.minor.patch version
      - key: DEBUG # Ensure DEBUG is False in production
        value: False
      # Render injects RENDER_EXTERNAL_HOSTNAME, used in settings.py
      - key: ALLOWED_HOSTS_ENV # Name for the environment variable read in settings.py
        value: ${RENDER_EXTERNAL_HOSTNAME} # Render provides the deployed hostname
      # Add this if you didn't hardcode DEBUG=False in settings.py
      # - key: DEBUG
      #   value: False 