databases:
  - name: training_tracker_db # Choose a name for your Render database service
    plan: free # Or choose a paid plan
    databaseName: training_tracker # The actual database name inside PostgreSQL
    user: training_tracker_user # The user for the database

services:
  - type: web
    plan: free # Or choose a paid plan
    name: training-tracker-app # Choose a name for your Render web service
    runtime: python
    buildCommand: "./build.sh"
    # Use the correct path to your ASGI application
    startCommand: "python -m gunicorn training_tracker.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: training_tracker_db # Must match the database service name above
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a secret key
      - key: WEB_CONCURRENCY
        value: 4 # Adjust based on your plan/needs
      # Add this if you didn't hardcode DEBUG=False in settings.py
      # - key: DEBUG
      #   value: False 